version: '3.1'
services:
  app:
    build: .
    ports:
      - "8120:8007"
  db:
    image: postgres:11
    restart: always
    #container_name: postgres-todolist
    ports:
      - "5432:5432"
    volumes:
      - my_postgress:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=todolist
      - POSTGRES_USER=todolist
      - POSTGRES_DB=todolist
volumes:
  my_postgress:
